site_name: PUERTOS DE RED - definición y uso

docs_dir: "md"
site_dir: "docs"

theme: mkdocs

nav:
    - Home: index.md
    - Puertos:
      - 1 - Definición: 1-Puertos/definicion.md
      - 2 - Puerto TCP/UDP: 1-Puertos/puerto_tcp_udp.md
      - 3 - Puertos de la Capa de Red: 1-Puertos/capa_red.md
      - 4 - Tipos de puertos: 1-Puertos/tipos_puertos.md
    - Seguridad conexiones:
      - 1 - Mejoras en los puertos: 2-Seguridad/mejoras_puertos.md
      - 2 - Seguridad para abrir puertos: 2-Seguridad/seguridad_abrir_puertos.md
      - 3 - Peligros en las conexiones: 2-Seguridad/peligro_conexiones.md
    - About: about.md


extra_css:
  - css/extra.css


